# -*- coding: utf-8 -*-
"""fake_news_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_behM_NzIfvRarH4Cd-1RFE6V7Or6en
"""

import random
names = [
    # Politics
    "Narendra Modi",
    "Amit Shah",
    "Sonia Gandhi",
    "Rahul Gandhi",
    "Arvind Kejriwal",
    "Yogi Adityanath",

    # Bollywood
    "Shah Rukh Khan",
    "Salman Khan",
    "Amitabh Bachchan",
    "Deepika Padukone",
    "Alia Bhatt",
    "Ranbir Kapoor",

    # Cricket
    "Virat Kohli",
    "Rohit Sharma",
    "Sachin Tendulkar",
    "M. S. Dhoni",
    "Hardik Pandya",
    "Smriti Mandhana",

    # Business & Tech
    "Mukesh Ambani",
    "Ratan Tata",
    "Gautam Adani",
    "Sundar Pichai",
    "N. R. Narayana Murthy",
    "Byju Raveendran",

    # Music & Art
    "A. R. Rahman",
    "Arijit Singh",
    "Neha Kakkar",
    "Shreya Ghoshal",
    "Sonu Nigam",
    "Zakir Hussain"
]
actions = [
    "discovers",
    "steals",
    "builds",
    "destroys",
    "paints",
    "cooks",
    "launches",
    "hides",
    "buys",
    "sells",
    "designs",
    "wins",
    "loses",
    "eats",
    "dances with",
    "sings about",
    "invents",
    "invests in",
    "flies to",
    "transforms into",
    "runs away with",
    "hosts",
    "declares",
    "captures",
    "celebrates",
    "marries",
    "adopts"
]
things = [
    "a giant pizza",
    "the moon’s cheese",
    "a diamond car",
    "an underwater city",
    "a chocolate planet",
    "a 200-foot dosa",
    "a talking parrot",
    "a golden rickshaw",
    "a flying auto",
    "a time machine",
    "a robot elephant",
    "a cricket bat made of gold",
    "a saree made of clouds",
    "a palace of samosas",
    "a river of chai",
    "a magical kulfi",
    "a floating laptop",
    "a spaceship shaped like a jalebi",
    "a Bollywood script",
    "a dancing cow",
    "a rainbow scooter",
    "a phone made of laddus",
    "a singing coconut",
    "a temple of chocolate",
    "a banana-shaped car"
]

print("welcome to fake headlines news genrator")
while True:
  namess = random.choice(names)
  actionss = random.choice(actions)
  thingss = random.choice(things)

  headline = f"here is fake headline who make you laugh:\n {namess} {actionss} {thingss}"
  print(headline)

  ask = input("would you like to see another news (yes/no)").strip().lower()
  if ask == "no":
    break

print("thank you for using this fake news headline genrator good day")